name: Build All
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.13.1'
      - name: Check out code
        uses: actions/checkout@v3
      - name: Build
        run: make all
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: bin/*
          draft: true
